[package]
name = "niiiice"
version = "0.1.0"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"

[lib]
name = "niiiice"
crate-type = ["cdylib"] 

[dependencies]
bee-crypto = { git = "https://github.com/Alex6323/bee-p" }
bee-ternary = { git = "https://github.com/Alex6323/bee-p" }